services:
  hackit-frontend-sample:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hackit-frontend-sample"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: npm run dev